[build-system]
requires = ["setuptools>=65.6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "setsim"
description = "Summing similarity measure for the Human Phenotype Ontology"
authors = [
    { name = "Ben Coleman", email = "ben.coleman@jax.org" },
    { name = "Daniel Danis", email = "daniel.gordon.danis@protonmail.com" },
    { name = "Peter Robinson", email = "peter.robinson@jax.org" },
]

readme = "README.md"
requires-python = ">=3.8"
keywords = ["human phenotype ontology", "HPO", "library"]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dynamic = ["version"]

dependencies = [
    "hpo-toolkit >= 0.3.0",
    "phenopackets >= 2.0.2, <3.0.0",
    "pandas >= 2.2.3",
    "tqdm >= 4.62.0"
]
[project.optional-dependencies]
test = ["pytest>=7.0.0, <=9.0.0"]

[project.urls]
"Repository" = "https://github.com/monarch-initiative/setsim"

[tool.setuptools]
package-dir = { "" = "src" }
zip-safe = false

[tool.setuptools.dynamic]
version = { attr = "setsim.__version__" }
